# Generated by Django 2.1.14 on 2019-11-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
