# Generated by Django 2.1.14 on 2019-11-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191129_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品名称', 'verbose_name_plural': '产品管理'},
        ),
    ]
