# Generated by Django 2.1.14 on 2019-12-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191129_1643'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='用例名称')),
                ('apiurl', models.CharField(max_length=200, verbose_name='接口URL')),
                ('apiparamvalue', models.CharField(max_length=800, verbose_name='接口参数和值')),
                ('apimethod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch')], default='0', max_length=200, null=True, verbose_name='接口方法')),
                ('apiresult', models.CharField(max_length=200, verbose_name='接口预期结果')),
                ('apiresponse', models.CharField(max_length=5000, null=True, verbose_name='响应数据')),
                ('apistatus', models.BooleanField(verbose_name='测试结果')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '单一接口用例',
                'verbose_name_plural': '单一接口用例',
            },
        ),
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '流程场景', 'verbose_name_plural': '流程场景接口'},
        ),
    ]
